---

- name: Setup a simple buildbot with one slave
  hosts: webservers
  sudo: yes
  sudo_user: root
  remote_user: "{{ remote_user }}"
  vars_files:
    - vars/vault/secret_key.yml
    - roles/webserver/vars/main.yml
  roles:
    - buildbot
