---
- name: reload nginx
  service: name=nginx state=reloaded
  sudo_user: root

- name: restart nginx
  service: name=nginx state=restarted
  sudo_user: root

- name: kill gunicorn
  shell: "{{ project_scripts }}/kill_gunicorn.sh"
  sudo_user: root

- name: start supervisord
  service: name=supervisor state=started
  sudo_user: root

- name: reload supervisor 
  shell: supervisorctl reload
  sudo_user: root
  
- name: restart supervisor
  service: supervisor restart 
  sudo_user: root
