---
  
- name: Pull sources from the repository.
  git: repo={{ project_repo }} 
       dest={{ project_code_real }}
       version={{ branch }}
       accept_hostkey=true

- name: Make the static files readable
  shell: "chown -R 777 {{ project_code_real }}/static/*"
  
- name: Install requirements to virtual environment.
  pip: requirements="{{ project_code_real }}/requirements.txt"
       virtualenv={{ project_venv_real }}
  notify:
    - kill gunicorn
       
- name: Sync the database and restart the server. 
  django_manage: command=syncdb
                 app_path={{ project_code }}
                 virtualenv={{ project_venv }}
  notify: 
    - restart supervisor
